### ISSUE TITLE
Failed to upgrade to version 4.0.0

### ISSUE THREAD

**Issue by danny-su** [leoafarias/homebrew-fvm#21]
`==> Downloading https://github.com/leoafarias/fvm/archive/4.0.0.tar.gz
Already downloaded: /Users/danny/Library/Caches/Homebrew/downloads/65c3eed92583af8062ff222308bdf1139930b689095cf2a8552eea245cf0aad3--fvm-4.0.0.tar.gz
==> Upgrading leoafarias/fvm/fvm
  3.2.1 -> 4.0.0 
==> /opt/homebrew/Cellar/fvm/4.0.0/libexec/bin/dart pub get
Last 15 lines from /Users/danny/Library/Logs/Homebrew/fvm/01.dart.log:
2025-10-31 02:35:50 +0000

/opt/homebrew/Cellar/fvm/4.0.0/libexec/bin/dart
pub
get

Resolving dependencies...
The current Dart SDK version is 3.2.6.

Because pubspec_parse 1.5.0 requires SDK version ^3.6.0 and no versions of pubspec_parse match >1.5.0 <2.0.0, pubspec_parse ^1.5.0 is forbidden.
So, because fvm depends on pubspec_parse ^1.5.0, version solving failed.

You can try the following suggestion to make the pubspec resolve:
* Try using the Dart SDK version: 3.9.2. See https://dart.dev/get-dart.

If reporting this issue please do so at (not Homebrew/* repositories):
  https://github.com/leoafarias/homebrew-fvm/issues`

<img width="1004" height="566" alt="Image" src="https://github.com/user-attachments/assets/bcd6723e-f707-4038-807c-db6c58fd2003" />

**Comment by nikitenich** [comment]
Fixed in https://github.com/leoafarias/homebrew-fvm/pull/20

**Comment by rakesh-oasys** [comment]
Not fixed yet. Getting the same issue.


brew install fvm
==> Fetching downloads for: fvm
==> Fetching leoafarias/fvm/fvm
==> Downloading https://storage.googleapis.com/dart-archive/channels/stable/release/3.2.6/
Already downloaded: /home/oasys/.cache/Homebrew/downloads/038b2d7334829cad6f76c039b5173e60d7e6cbe0ca793651ac00c45ea1616f8c--dartsdk-linux-x64-release.zip
==> Downloading https://github.com/leoafarias/fvm/archive/4.0.0.tar.gz
Already downloaded: /home/oasys/.cache/Homebrew/downloads/65c3eed92583af8062ff222308bdf1139930b689095cf2a8552eea245cf0aad3--fvm-4.0.0.tar.gz
==> Installing fvm from leoafarias/fvm
==> /home/linuxbrew/.linuxbrew/Cellar/fvm/4.0.0/libexec/bin/dart pub get
Last 15 lines from /home/oasys/.cache/Homebrew/Logs/fvm/01.dart.log:

/home/linuxbrew/.linuxbrew/Cellar/fvm/4.0.0/libexec/bin/dart
pub
get

Resolving dependencies...
The current Dart SDK version is 3.2.6.

Because pubspec_parse 1.5.0 requires SDK version ^3.6.0 and no versions of pubspec_parse match >1.5.0 <2.0.0, pubspec_parse ^1.5.0 is forbidden.
So, because fvm depends on pubspec_parse ^1.5.0, version solving failed.


You can try one of the following suggestions to make the pubspec resolve:
* Try using the Dart SDK version: 3.9.2. See https://dart.dev/get-dart.
* Consider downgrading your constraint on pubspec_parse: dart pub add pubspec_parse:^1.4.0

If reporting this issue please do so at (not Homebrew/* repositories):
  https://github.com/leoafarias/homebrew-fvm/issues

These open issues may also help:
leoafarias/fvm/fvm 2.4.1 did not build https://github.com/leoafarias/homebrew-fvm/issues/15

**Comment by yesseruser** [comment]
> Not fixed yet. Getting the same issue.
> 
> brew install fvm ==> Fetching downloads for: fvm ==> Fetching leoafarias/fvm/fvm ==> Downloading https://storage.googleapis.com/dart-archive/channels/stable/release/3.2.6/ Already downloaded: /home/oasys/.cache/Homebrew/downloads/038b2d7334829cad6f76c039b5173e60d7e6cbe0ca793651ac00c45ea1616f8c--dartsdk-linux-x64-release.zip ==> Downloading https://github.com/leoafarias/fvm/archive/4.0.0.tar.gz Already downloaded: /home/oasys/.cache/Homebrew/downloads/65c3eed92583af8062ff222308bdf1139930b689095cf2a8552eea245cf0aad3--fvm-4.0.0.tar.gz ==> Installing fvm from leoafarias/fvm ==> /home/linuxbrew/.linuxbrew/Cellar/fvm/4.0.0/libexec/bin/dart pub get Last 15 lines from /home/oasys/.cache/Homebrew/Logs/fvm/01.dart.log:
> 
> /home/linuxbrew/.linuxbrew/Cellar/fvm/4.0.0/libexec/bin/dart pub get
> 
> Resolving dependencies... The current Dart SDK version is 3.2.6.
> 
> Because pubspec_parse 1.5.0 requires SDK version ^3.6.0 and no versions of pubspec_parse match >1.5.0 <2.0.0, pubspec_parse ^1.5.0 is forbidden. So, because fvm depends on pubspec_parse ^1.5.0, version solving failed.
> 
> You can try one of the following suggestions to make the pubspec resolve:
> 
>     * Try using the Dart SDK version: 3.9.2. See https://dart.dev/get-dart.
> 
>     * Consider downgrading your constraint on pubspec_parse: dart pub add pubspec_parse:^1.4.0
> 
> 
> If reporting this issue please do so at (not Homebrew/* repositories): https://github.com/leoafarias/homebrew-fvm/issues
> 
> These open issues may also help: leoafarias/fvm/fvm 2.4.1 did not build [#15](https://github.com/leoafarias/homebrew-fvm/issues/15)

It's an open PR, not merged yet
